authors = ["Daniel Cloud"]
description = "All natural pine, faux fur, and a bit of soho vibes – a classy minimalist theme for Zed."
id = "rose-pine-minimal-theme"
name = "Rosé Pine Minimal"
repository = "https://github.com/dcloud/rose-pine-minimal-theme"
schema_version = 1
version = "1.3.2"
